
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { a } from '@react-spring/three'

const Island = (props) => {
  const islandRef = useRef()

  const { nodes, materials } = useGLTF('/assets/3d/island.glb')

  return (
    <a.group ref={islandRef} {...props}>
      <group position={[-1.541, 2.162, 1.136]} scale={[1.501, 1.181, 1.501]}>
        <mesh
          geometry={nodes.polySurface12_home_body_0.geometry}
          material={materials.home_body}
        />
        <mesh
          geometry={nodes.polySurface1336_wood_0.geometry}
          material={materials.wood}
        />
        <mesh
          geometry={nodes.polySurface1467_wood_0.geometry}
          material={materials.wood}
        />
      </group>

      <group
        position={[-0.686, 13.571, 2.281]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[2.34, 3.321, 4.929]}
      >
        <mesh
          geometry={nodes.polySurface16_roof1_0.geometry}
          material={materials.roof1}
        />
        <mesh
          geometry={nodes.polySurface16_windows_background_0.geometry}
          material={materials.windows_background}
        />
        <mesh
          geometry={nodes.polySurface16_roof3_0.geometry}
          material={materials.roof3}
        />
        <mesh
          geometry={nodes.polySurface17_windows_frame_0.geometry}
          material={materials.windows_frame}
        />
      </group>
    </a.group>
  )
}

useGLTF.preload('/assets/3d/island.glb')


       
 

export default Island;
